### ISSUE TITLE
epanet2toolkit with EPANET 2.2

### ISSUE THREAD

**Issue by emmaliulu** [bradleyjeck/epanet2toolkit#18]
Is there any way I could use epanet2toolkit with EPANET 2.2 (https://github.com/USEPA/epanet-solver/releases/tag/v2.2.0-beta.2)? The epanet-solver contains epanet2 toolkit library, but I'm not quite sure how to integrate it with the epanet2toolkit R package. Any advice?

**Comment by bradleyjeck** [comment]
Hi @emmaliulu,  that's a good question. Using any version of EPANET with R requires a wrapper/shim/bridge layer between EPANET and R.   A further description of this is in the [Programming Notes for Package Developers](https://github.com/bradleyjeck/epanet2toolkit/#programming-notes-for-package-developers) section of the readme.  In the case of EPANET version 2.1, that layer is part of the R package epanet2toolkit.  To call the newer epanet version you could follow:
* https://github.com/bradleyjeck/epanet2toolkit/blob/master/src/Repanet2.c  to write C functions that are callable from R; and 
* https://github.com/bradleyjeck/epanet2toolkit/blob/master/R/epanet.r  to write R functions that call the C functions above. 

Once the 2.2 version of epanet is finalized, I hope to upgrade the epanet2toolkit package to include it.

**Comment by bradleyjeck** [comment]
Hi @emmaliulu  - Support for the epanet 2.2 functions is now available in version 1.0.0 of epanet2toolkit, now available on CRAN.
