### ISSUE TITLE
How to detect errors or warnings when simulating via toolkit?

### ISSUE THREAD

**Issue by petacoder75** [bradleyjeck/epanet2toolkit#2]
I am doing thousands of epanet simulations from R. I want to know when a simulation generates warnings or errors like negative pressure, for example.

Is it possible to get error or warning codes via toolkit? I do not want to parse the rpt file on disk because it is to slow for me.

Performance is very important in my case.

**Comment by bradleyjeck** [comment]
Hi @petacoder75 - Cool to hear that you're running lots of simulations.  Toolkit functions return one of the error codes listed at the following link, but negative pressures are not among them. Errors returned from epanet are passed back up to R by the package functions.  https://github.com/OpenWaterAnalytics/EPANET/wiki/Error-Codes    

One way to figure out when a simulation generates negative pressures without parsing a report file would be to write your own R function that runs the simulation step-by-step, checking after each step to see if any pressures are negative.

**Comment by petacoder75** [comment]
Hi @bradleyjeck and thanks a lot for the package and your support.

- Getting Errors: How can I detect programmatically that the simulation returns an error? Could you please send an example?

- Checking negative pressures: How can I check the pressure value of all the nodes without reading the report file? I want to avoid to write/read on/from disk to optimize speed? Any example?

Thanks a lot!!!

**Comment by bradleyjeck** [comment]
Hi @petacoder75 - glad the package is useful for you. 

You can see an error come back from epanet for example if you try to open a file that isn't there:
```
ENopen("nofile.inp", "nofile.rpt")
```
 or access a node or link that doesn't exist: 
```
# path to Net1.inp example file included with this package
inp <- file.path( find.package("epanet2toolkit"), "extdata","Net1.inp")
ENopen( inp, "Net1.rpt")
# there is no node with index 999
ENgetnodevalue(999, "EN_BASEDEMAND")
ENclose()
```

For the pressures, have a look at the hydrant rating example:
https://github.com/bradleyjeck/epanet2toolkit/blob/master/tests/testthat/test_epanet_example_2.r
You'll want to iterate over all the nodes rather than just tracking one node though.

**Comment by petacoder75** [comment]
Hi @bradleyjeck thank's for your support.

 I have solved my problem with the following code:


 y <- function(my.path){
    ENepanet(paste(my.path,"epanet_to_simulate.inp",sep = ""), paste(my.path,"epanet_to_simulate.rpt",sep = ""))  
  }
  
  sim.diagnostic <- tryCatch(y(my.path),error=function(e) e, warning=function(w) w)
  
  if(is(sim.diagnostic,"error")){
    
    print("There is an error");
    
  } else if(is(sim.diagnostic,"warning")){  
    
        print("There is a warning");
    
  }else{
    
        print("Simulation was OK");
  }
