### ISSUE TITLE
ENgetlinkvalue(2, "EN_HEADLOSS")

### ISSUE THREAD

**Issue by agprats** [bradleyjeck/epanet2toolkit#27]
Headlosses obtained using the code ENgetlinkvalue(2, "EN_HEADLOSS") and the one obtained in epanet or in the report are different. However ENgetlinkvalue(2, "EN_FLOW"), ENgetlinkvalue(2, "EN_VELOCITY") or ENgetlinkvalue(2, "EN_LENGH") are exactly the same

**Comment by bradleyjeck** [comment]
I am able to duplicate this error looking at the example network 3 (Net3.inp).  However, i think this on the epanet side rather than the R package.

**Comment by agprats** [comment]
I've checked this error happens always regardless the network. 
Would be possible the R package is not obtaining the headlosses properly?

**Comment by bradleyjeck** [comment]
Looking at it again, I don't think this is actually a bug. The report file prints head loss per 1000 feet while the toolkit function extracts the total head loss for the link.  So multiplying the value in the report file by the link_length / 1000 should give the value returned by ENgetlinkvalue.

**Comment by agprats** [comment]
Exactly!!!
That's correct.
Thank you Brad
