### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by petacoder75** [bradleyjeck/epanet2toolkit#3]
When I run many simulations (using ENepanet function), after some iterations (more than 3000) I get following error: 

> Too many open files

I have checked the number of open files with following function:

simOpenFiles <- function() {
      kk <- trimws(system("lsof -a -d 1-99999 -p $PPID | wc -l", intern = TRUE));
    }

I see how after calling ENepanet function, the number of open files increases.

I think the problem is that the hydraulics file remains open. I see files with names like this: "enHqhLQV"

Any work-around?

**Comment by petacoder75** [comment]
I have found the problem.  The **getTmpName** leaves the hydraulical files open if you work on an linux/mac environment. 

I have done a change to the epanet.c file to solve the problem. Attached you will find my change ([epanet.c.zip](https://github.com/bradleyjeck/epanet2toolkit/files/1587646/epanet.c.zip)).

Please include it in a new release of the epanet2toolkit package.

The changes are in lines 129, 2881 and 2882.

**Comment by bradleyjeck** [comment]
@petacoder75 looks like a good catch.  The function mkstemp() actually creates a file, not just a filename.  

Could you send me the change as a pull request?  

After a bit of testing we can also send the change to the [upstream repo for epanet.](https://github.com/OpenWaterAnalytics/EPANET)
