### ISSUE TITLE
Request for Adding Functions to epanet2toolkit Package

### ISSUE THREAD

**Issue by gutompf** [bradleyjeck/epanet2toolkit#34]
Dear Developers,
I hope this message finds you well. I wanted to express my gratitude for the excellent epanet2toolkit package you have created. It has been a valuable resource for me and many others in the water engineering community.
I am writing to request if you could consider adding the following OWE functions to the package: EN_setlinknodes(), EN_addlink(), EN_addnode(), EN_deletelink(), and EN_deletenode(). These functions would greatly improve the package's functionality.
Thank you for your time and consideration.
Best regards,
Milan (milan.cisty@stuba.sk)

**Comment by bradleyjeck** [comment]
Hi Milan - I'm pleased to let you know that support for these functions is now available in version 1.0.0 of the package that is now available on CRAN.

**Comment by gutompf** [comment]
Thank you very much,

Milan

 

Od: Brad Eck ***@***.***> 
Odoslané: štvrtok 2. novembra 2023 9:35
Komu: bradleyjeck/epanet2toolkit ***@***.***>
Kópia: gutompf ***@***.***>; Author ***@***.***>
Predmet: Re: [bradleyjeck/epanet2toolkit] Request for Adding Functions to epanet2toolkit Package (Issue #34)

 

Hi Milan - I'm pleased to let you know that support for these functions is now available in version 1.0.0 of the package that is now available on CRAN.
