### ISSUE TITLE
A leakage model in epanet2toolkit?

### ISSUE THREAD

**Issue by aigualenc** [bradleyjeck/epanet2toolkit#35]
Dear epanet2toolkit users,

I'd like to add a leakage model to the EPANET models. I've found that EPANET3 or epanet-dev (https://github.com/OpenWaterAnalytics/epanet-dev/blob/develop/doc/Differences%20From%20EPANET2.md) indeed incorporate that functionality (LEAKAGE_MODEL, Choice of pipe leakage model), I guess a way to manage more efficiently the emitters objects of EPANET2.2. 

Is there any way to incorporate or use a leakage model within epanet2toolkit? Or alternatively, is there any way to integrate or link epanet2toolkit package to epanet-dev?

All the best,

Josep M. Campanera, 
water auditor

**Comment by bradleyjeck** [comment]
Hi @aigualenc - Thank you for your interest in epanet2toolkit. The leakage models mentioned above are not supported in epanet version 2.2 and that is the version currently supported by the R package.   As for integrating epanet-dev, while possible in principle it would probably end up as a new package.
