### ISSUE TITLE
Use of toolkit with Rshiny

### ISSUE THREAD

**Issue by algorithmik** [bradleyjeck/epanet2toolkit#6]
Thank you for this package. It is great. 

I have used it to make an online tool using rshiny (http://www.algorithmik.org.au/apps/aqualibrium/). I would like to note one issue when I deployed it to the server ... which is that I would like to have a toolkit function to set the path for the temporary files that epanet creates. I could not see how to set this functionality ... but my apologies if it is actually there.

Currently epanet uses whatever is the global path variable is inside R, e.g. setwd("/path/to/somewhere"), but Rshiny does not allow setting the global environment variable like this when you deploy to the server (see https://support.rstudio.com/hc/en-us/articles/231249288-Why-does-my-app-work-locally-but-not-on-my-Shiny-Server-) ... so it would be good to be able to control the path to temporary files without using the global path variable. The workaround is to give write permissions to the server folder where my code resides ... but I would prefer to keep the live code and working directories separate if I can. 

Thanks again.

**Comment by bradleyjeck** [comment]
Hi @algorithmik, Glad the package is useful for you.  Feel free to include a shout-out on your web page and/or give the repo a :star:  :wink:

I think you can control where the temporary files are written by supplying the 3rd argument to ENopen as described in the [Epanet docs](https://github.com/OpenWaterAnalytics/EPANET/wiki/Output-File).   

Thus you could write
```
ENopen( "path/to/some/network.inp",
               "path/to/simulation/reports/network.rpt/, 
               "path/to/temp/files/network.bin")
```

Let me know if that works?
