### ISSUE TITLE
How to produce full report instead of status report

### ISSUE THREAD

**Issue by emmaliulu** [bradleyjeck/epanet2toolkit#7]
I run a full simulation using ENepanet, but instead of a full report, it produced a status report which shows two lines of warning messages. I also get these warning messages when I ran my INP file in the EPANET interface. But I could also generate a full report through the interface. Is there any way to show the full report using ENepanet function?

**Comment by bradleyjeck** [comment]
Hi @emmaliulu - when running with ENepanet, reporting is controlled by the [REPORT] section of the .inp file as described in the [epanet user manual](http://nepis.epa.gov/Adobe/PDF/P1007WWU.pdf) on page 161.   

The tl;dr is that an inp file with the following will output link and node results 
>[REPORT]
> Nodes All 
> Links All

Once you have a report file, you can read it into R with [epanetReader](http://github.com/bradleyjeck/epanetReader). 

Hope this helps

**Comment by emmaliulu** [comment]
Problem solved! Thank you very much!
